### ISSUE TITLE
skin art bot doesnt work

### ISSUE THREAD

**Issue by astella6969** [6uf/mcsn#1]
![image](https://user-images.githubusercontent.com/73035469/164888392-cb8c5329-16cf-4acb-ae76-694401a1430c.png)

**Comment by 6uf** [comment]
A few problems here.. 

1. it doesnt seem you have bearers in your config.json file to fix this just input no for that. (your enter your accs email:password from the terminal)
2. it also appears that it cant find the images folder, along with the png for the template skin, i suggest downloading that from here again https://github.com/6uf/mcsn/tree/main/images

The error your getting is because of multiple reasons, there is no bearers so no skin changes can be made, there is no base.png variable because it is unable to detect one.. 

a small tutorial:

go run . namemc -n NameOfYourArt -i imagename.png (or jpg)

the imagename.png needs to be inside the images folder where your mcsn is stored. <3

**Comment by 6uf** [comment]
also the names i used in the command above is just examples you can name the image anything and the skin art anything.

the skin art will make a folder based on the name you use,

images
           > NameArtYouUsed
                                          > all the png images of the skin art...

i hope this clears up some stuff.

**Comment by astella6969** [comment]
Thanks @6uf it works now but why do i have to do it manually? doesnt it have to manually set the skin every minute or 2

**Comment by 6uf** [comment]
you can go through and change the skin on the minecraft site, but it takes a long time to do that. just between every skin change make sure to refresh the namemc page until it caches the skin into the skin history :3

**Comment by 6uf** [comment]
sorry if i dont reply much, i been very busy

**Comment by astella6969** [comment]
> you can go through and change the skin on the minecraft site, but it takes a long time to do that. just between every skin change make sure to refresh the namemc page until it caches the skin into the skin history :3

Yeah but i need it to be automatically not manually
